#define PIN_OLED_MISO GPIO_NUM_19
#define PIN_OLED_MOSI GPIO_NUM_23
#define PIN_OLED_CLK GPIO_NUM_18
#define PIN_OLED_CS GPIO_NUM_5
#define PIN_OLED_A0 GPIO_NUM_16
#define PIN_OLED_RST GPIO_NUM_17

#define PIN_ENCODER_A GPIO_NUM_2		// CLK
#define PIN_ENCODER_B GPIO_NUM_4		// DT
#define PIN_ENCODER_BTN GPIO_NUM_0		// SW
